### ISSUE TITLE
nix-shell fails to build

### ISSUE THREAD

**Issue by codygman** [GuillaumeDesforges/haskell-nix-dev-template#4]
I noticed nixpkgs isn't pinned by default, I think maybe it should be to prevent this? I put the build log at the bottom for the run from `97c1cb5`.

I wasn't sure how to pass in `usePinnedNixPkgs so I made this change:

```diff
diff --git a/nix/nixpkgs.nix b/nix/nixpkgs.nix
index 5e0f958..884bad8 100644
--- a/nix/nixpkgs.nix
+++ b/nix/nixpkgs.nix
@@ -12,4 +12,4 @@ let
   # Or the current local
   current-local = import <nixpkgs> {};
 in
-  if usePinnedNixpkgs then pinned-nixpkgs else current-local
\ No newline at end of file
+  pinned-nixpkgs
```

But when I ran it something was wrong:

```shell
[cody@nixos:~/haskell-nix-dev-template]$ nix-shell
error: attempt to call something which is not a function but a set, at /home/cody/haskell-nix-dev-template/nix/nixpkgs.nix:10:20
```

build log:

```
building '/nix/store/7g7ffxnlm55vhvv8j61p4sjq80n3a286-zlib-0.6.2.1-lib-zlib-config.drv'...
cannot build derivation '/nix/store/69x9904w580mmnr43bzwpdmv8ab4zjnk-criterion-1.5.6.2.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/jklrfdilhk2cfjvksm5mhlh9hawi0x9a-hoogle-5.0.17.15.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/drdlsa56j0ayl074s74y7s97cjia8nm0-hoogle-local-0.1.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/8wz5lc8c1kb36rpkmsdgy1c4q307qsvd-network-uri-2.6.3.0.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/bmbfspdmn5rfwqiz4i5zbygw5d73g9hw-cabal-install-3.0.0.0.drv': 1 dependencies couldn't be built
error: build of '/nix/store/azl556sg679y5zbg11mgf0vgr9v08ymw-ghc-8.6.5-with-packages.drv', '/nix/store/bmbfspdmn5rfwqiz4i5zbygw5d73g9hw-cabal-install-3.0.0.0.drv', '/nix/store/slac0frwvlmd8f3h50lh2kzpd7f1znbb-ghcide-0.1.0-exe-ghcide.drv' failed
```

**Comment by GuillaumeDesforges** [comment]
Thanks for the issue.

Could you please refer to https://github.com/GuillaumeDesforges/haskell-nix-dev-template/pull/5 and test the branch on your side ?
Once we have confirmed it's working for you I'll merge.

**Comment by codygman** [comment]
Hi @GuillaumeDesforges , thank you so much for fixing this (and quickly!). I can confirm it is working now.

**Comment by codygman** [comment]
Actually it looks like when I do `code .` from within `haskell-nix-dev-template` it doesn't have the nix-environment selector. I tried installing it manually and it says:

```
Unable to install 'arrterian.nix-env-selector' extension because it is not compatible with the current version of VS Code (version 1.35.1).
````

I think you might consider this a breaking change since you want someone to be able to start developing right away.

**Comment by codygman** [comment]
I'll set it to unstable and see if this fixes the code extension but maybe it's the reverse problem and requires an earlier vresion of vscode?

Here's what I'm trying to see if everything works with:

```diff
diff --git a/nix/config.nix b/nix/config.nix
index 7830bf5..53ba4ec 100644
--- a/nix/config.nix
+++ b/nix/config.nix
@@ -9,6 +9,6 @@
   use-pinned-nixpkgs = true;
   # if set to true, set url, ref and revision of pinned nixpkgs
   pinned-nixpkgs-url = https://github.com/nixos/nixpkgs-channels/;
-  pinned-nixpkgs-ref = "refs/heads/nixos-19.09";
-  pinned-nixpkgs-rev = "107ffbb22ad7920cb3c694dcc1d032a39e003b14";
-}
\ No newline at end of file
+  pinned-nixpkgs-ref = "refs/heads/nixos-unstable";
+  pinned-nixpkgs-rev = "a2e06fc3423c4be53181b15c28dfbe0bcf67dd73";
+}
```

**Comment by codygman** [comment]
Oh, this doesn't install it's own vs code yet and that's what #1 is about? I had vscode 1.35 which is why I had an issue. It would be nice to install vscode with all of this as well and have it behave correctly inside of `nix-shell --pure` for instance.

This is awesome btw, thank you for your hard work!

**Comment by GuillaumeDesforges** [comment]
> Oh, this doesn't install it's own vs code yet and that's what #1 is about? I had vscode 1.35 which is why I had an issue. It would be nice to install vscode with all of this as well and have it behave correctly inside of `nix-shell --pure` for instance.

Yes, for now the env does not have VS Code installed.

> This is awesome btw, thank you for your hard work!

My pleasure, hope it helps
